name: Intern Assessment
on: [pull_request]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install
      - name: Run Selected Tests
        run: node scripts/test-selector.js
      - name: Generate Report
        run: node scripts/generate-report.js
      - uses: actions/upload-artifact@v3
        with:
          name: Test Report
          path: report.pdf